server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  # DataSourceProperties
  datasource:
    url: jdbc:mysql://localhost:3306/nklt?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
      file-size-threshold: 0MB


# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xrj.entity
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true

#pagehelper??????
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




